version: '2'

services:
  backend:
    build: ./be/app
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./be/app/:/usr/src/protecrud/be/
    ports:
      - 9000:9000
    env_file:
      - ./be/.env.dev
    depends_on:
      - database
  frontend:
    build: ./fe/app
    volumes:
      - ./fe/app/:/usr/src/protecrud/fe/
      - /fe/node_modules
    ports:
      - 4200:4200
    depends_on:
      - backend
  database:
    image: postgres:15.2
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=V9rj0kmE#e0R
      - POSTGRES_DB=backend_dev
  
volumes:
  postgres_data: