# Generated by Django 4.2.1 on 2023-05-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='amount',
            new_name='quantity',
        ),
    ]
